require 'spree_core'
require 'spree_editor/version'
require 'spree_editor/engine'
require 'spree_editor/editor_settings'
require 'coffee_script'
require 'tinymce-rails'
require 'ckeditor'
require 'spree_extension'
